### ISSUE TITLE
Release Roadmap

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#12]
Here's a map of what we need to do before we can start pushing CKAN to the world.
## Meta
- [x] Stabilise spec
## Client
- [x] Support basic download and install
- [x] Cache download zip files
- [x] Detect/Cache installed CKAN meta-data
- [x] Support downloading CKAN index
- [x] Build test framework ( #5)
- [x] Make sure we're easy to build under Visual Studio and MonoDevelop
## Cloud
- [x] Find hosting for CKAN index (estimated size ~ 2 MB, probably github for now)
## Module Dev
- [ ] Invite friendly mod authors to participate (comment below if this is you!)
- [ ] Prepare CKAN files for popular mods
- [ ] Trigger auto-generation of CKAN files on module release (#2)
