### ISSUE TITLE
Build Process in CKAN-meta - failure is success

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1273]
A number of things occurred that I think should have caused a failure on this build. It likely needs a good overhaul like KSP-CKAN/NetKAN#1423

```bash
GitHub pull request #1875 of commit ad5ef0af04301f339fc5c02e02abed1852905264, no merge conflicts.
Setting status of ad5ef0af04301f339fc5c02e02abed1852905264 to PENDING with url http://52.10.41.70/job/NetKAN/52/ and message: 'Build started sha1 is merged.'
Building remotely on Local Docker-156cd60b163b in workspace /home/jenkins/workspace/NetKAN
Cloning the remote Git repository
Cloning repository https://github.com/KSP-CKAN/NetKAN.git
 > git init /home/jenkins/workspace/NetKAN # timeout=10
Fetching upstream changes from https://github.com/KSP-CKAN/NetKAN.git
 > git --version # timeout=10
using GIT_SSH to set credentials Jenkins Key Pair
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5902947757995373339.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/KSP-CKAN/NetKAN.git +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
 > git config remote.origin.url https://github.com/KSP-CKAN/NetKAN.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/KSP-CKAN/NetKAN.git # timeout=10
Fetching upstream changes from https://github.com/KSP-CKAN/NetKAN.git
using GIT_SSH to set credentials Jenkins Key Pair
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git5580227904927360249.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/KSP-CKAN/NetKAN.git +refs/pull/*:refs/remotes/origin/pr/*
 > git config --local --remove-section credential # timeout=10
 > git rev-parse ad5ef0af04301f339fc5c02e02abed1852905264^{commit} # timeout=10
Checking out Revision ad5ef0af04301f339fc5c02e02abed1852905264 (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ad5ef0af04301f339fc5c02e02abed1852905264
 > git rev-list 9ecac38e168d0f8c0af27ba55d2759cd14248184 # timeout=10
[NetKAN] $ /bin/sh -xe /tmp/hudson968251256126226895.sh
+ bash -x /home/jenkins/workspace/NetKAN/build.sh
+ KSP_VERSION_DEFAULT=1.0.2
+ KSP_NAME_DEFAULT=dummy
+ LATEST_CKAN_URL=http://ckan-travis.s3.amazonaws.com/ckan.exe
+ LATEST_NETKAN_URL=http://ckan-travis.s3.amazonaws.com/netkan.exe
+ JQ_PATH=jq
+ rm -rf built
+ rm -rf downloads_cache
+ rm -f master.tar.gz
+ rm -f metadata.tar.gz
+ echo 'Running basic sanity tests on metadata.'
Running basic sanity tests on metadata.
+ echo 'If these fail, then fix whatever is causing them first.'
If these fail, then fix whatever is causing them first.
+ prove
t/inflate.t ... skipped: Not a travis pull request
t/metadata.t .. ok
All tests successful.
Files=2, Tests=4559,  1 wallclock secs ( 0.42 usr  0.03 sys +  0.83 cusr  0.04 csys =  1.32 CPU)
Result: PASS
+ echo 'Finding changes to test...'
Finding changes to test...
+ '[' -z ad5ef0af04301f339fc5c02e02abed1852905264 ']'
+ echo 'Commit hash: ad5ef0af04301f339fc5c02e02abed1852905264'
Commit hash: ad5ef0af04301f339fc5c02e02abed1852905264
++ git diff --diff-filter=AM --name-only --stat origin/master NetKAN
+ export COMMIT_CHANGES=NetKAN/GunstarAP.netkan
+ COMMIT_CHANGES=NetKAN/GunstarAP.netkan
+ '[' NetKAN/GunstarAP.netkan = '' ']'
+ echo 'Running jsonlint on the changed files'
Running jsonlint on the changed files
+ echo 'If you get an error below you should look for syntax errors in the metadata'
If you get an error below you should look for syntax errors in the metadata
+ jsonlint -s -v NetKAN/GunstarAP.netkan
NetKAN/GunstarAP.netkan: ok
+ mkdir built
+ mkdir downloads_cache
+ echo 'Fetching latest ckan.exe'
Fetching latest ckan.exe
+ wget --quiet http://ckan-travis.s3.amazonaws.com/ckan.exe -O ckan.exe
+ echo 'Fetching latest netkan.exe'
Fetching latest netkan.exe
+ wget --quiet http://ckan-travis.s3.amazonaws.com/netkan.exe -O netkan.exe
+ echo 'Fetching latest metadata'
Fetching latest metadata
+ wget --quiet https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz -O metadata.tar.gz
+ '[' -z ad5ef0af04301f339fc5c02e02abed1852905264 ']'
+ KSP_NAME=ad5ef0af04301f339fc5c02e02abed1852905264
++ pwd
+ mono --debug ckan.exe ksp add ad5ef0af04301f339fc5c02e02abed1852905264 /home/jenkins/workspace/NetKAN/dummy_ksp
276 [1] WARN CKAN.KSPManager (null) - 7f34b7dadea974cc5375c68adcf188057d88bd32 at /home/jenkins/workspace/PR builder - NetKAN metadata/NetKAN/dummy_ksp is not a vaild install
297 [1] WARN CKAN.KSPManager (null) - Auto-start instance was invalid: Exception of type 'CKAN.InvalidKSPInstanceKraken' was thrown.
Sorry, /home/jenkins/workspace/NetKAN/dummy_ksp does not appear to be a KSP directory
+ mono --debug ckan.exe ksp default ad5ef0af04301f339fc5c02e02abed1852905264
155 [1] WARN CKAN.KSPManager (null) - 7f34b7dadea974cc5375c68adcf188057d88bd32 at /home/jenkins/workspace/PR builder - NetKAN metadata/NetKAN/dummy_ksp is not a vaild install
Couldn't find install with name "ad5ef0af04301f339fc5c02e02abed1852905264", aborting..
+ echo Running ckan update
Running ckan update
+ mono --debug ckan.exe update
152 [1] WARN CKAN.KSPManager (null) - 7f34b7dadea974cc5375c68adcf188057d88bd32 at /home/jenkins/workspace/PR builder - NetKAN metadata/NetKAN/dummy_ksp is not a vaild install
I don't know where KSP is installed.
Use 'ckan ksp help' for assistance on setting this.
+ echo Running jsonlint on the changed files
Running jsonlint on the changed files
+ echo If you get an error below you should look for syntax errors in the metadata
If you get an error below you should look for syntax errors in the metadata
+ jsonlint -s -v NetKAN/GunstarAP.netkan
NetKAN/GunstarAP.netkan: ok
+ echo Fetching latest netkan.exe
Fetching latest netkan.exe
+ wget --quiet https://ckan-travis.s3.amazonaws.com/netkan.exe
+ mkdir built
mkdir: cannot create directory 'built': File exists
+ for f in '$COMMIT_CHANGES'
+ echo 'Running NetKAN for NetKAN/GunstarAP.netkan'
Running NetKAN for NetKAN/GunstarAP.netkan
+ mono netkan.exe NetKAN/GunstarAP.netkan --cachedir=downloads_cache --outputdir=built

Unhandled Exception:
CKAN.FileNotFoundKraken: Could not find GunstarAP directory in zipfile to install
  at CKAN.ModuleInstallDescriptor.ConvertFindToFile (ICSharpCode.SharpZipLib.Zip.ZipFile zipfile) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstallDescriptor.DefaultInstallStanza (System.String ident, ICSharpCode.SharpZipLib.Zip.ZipFile zipfile) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.FindInstallableFiles (CKAN.CkanModule module, ICSharpCode.SharpZipLib.Zip.ZipFile zipfile, CKAN.KSP ksp) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.FindInstallableFiles (CKAN.CkanModule module, System.String zip_filename, CKAN.KSP ksp) [0x00000] in <filename unknown>:0 
  at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: CKAN.FileNotFoundKraken: Could not find GunstarAP directory in zipfile to install
  at CKAN.ModuleInstallDescriptor.ConvertFindToFile (ICSharpCode.SharpZipLib.Zip.ZipFile zipfile) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstallDescriptor.DefaultInstallStanza (System.String ident, ICSharpCode.SharpZipLib.Zip.ZipFile zipfile) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.FindInstallableFiles (CKAN.CkanModule module, ICSharpCode.SharpZipLib.Zip.ZipFile zipfile, CKAN.KSP ksp) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.FindInstallableFiles (CKAN.CkanModule module, System.String zip_filename, CKAN.KSP ksp) [0x00000] in <filename unknown>:0 
  at CKAN.NetKAN.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
+ mono ckan.exe ksp forget dummy
151 [1] WARN CKAN.KSPManager (null) - 7f34b7dadea974cc5375c68adcf188057d88bd32 at /home/jenkins/workspace/PR builder - NetKAN metadata/NetKAN/dummy_ksp is not a vaild install
Couldn't find install with name "dummy", aborting..
+ for f in 'built/*.ckan'
+ echo 'Checking built/*.ckan'
Checking built/*.ckan
+ echo ----------------------------------------------
----------------------------------------------
+ echo ''

+ python -m json.tool
+ cat 'built/*.ckan'
cat: built/*.ckan: No such file or directory
No JSON object could be decoded
+ echo ----------------------------------------------
----------------------------------------------
+ echo ''

+ OTHER_FILES=()
+ for o in 'built/*.ckan'
+ '[' 'built/*.ckan' '!=' 'built/*.ckan' ']'
+ inject_metadata
+ '[' 0 -ne 1 ']'
+ echo 'Nothing to inject.'
Nothing to inject.
+ cp metadata.tar.gz master.tar.gz
+ return 0
++ jq .identifier 'built/*.ckan'
jq: built/*.ckan: No such file or directory
+ CURRENT_IDENTIFIER=
++ jq 'if .ksp_version then .ksp_version else .ksp_version_min end' 'built/*.ckan'
jq: built/*.ckan: No such file or directory
+ CURRENT_KSP_VERSION=
+ CURRENT_IDENTIFIER=
+ CURRENT_KSP_VERSION=
+ echo 'Extracted  as identifier.'
Extracted  as identifier.
+ echo 'Extracted  as KSP version.'
Extracted  as KSP version.
+ create_dummy_ksp ad5ef0af04301f339fc5c02e02abed1852905264
+ KSP_VERSION=1.0.2
+ KSP_NAME=dummy
+ '[' 1 -eq 2 ']'
+ '[' 1.0.2 == 0.90 ']'
+ echo 'Creating a dummy KSP 1.0.2 install'
Creating a dummy KSP 1.0.2 install
+ rm -rf dummy_ksp
+ mkdir dummy_ksp
+ mkdir dummy_ksp/CKAN
+ mkdir dummy_ksp/GameData
+ mkdir dummy_ksp/Ships/
+ mkdir dummy_ksp/Ships/VAB
+ mkdir dummy_ksp/Ships/SPH
+ mkdir dummy_ksp/Ships/@thumbs
+ mkdir dummy_ksp/Ships/@thumbs/VAB
+ mkdir dummy_ksp/Ships/@thumbs/SPH
+ echo 'Version 1.0.2'
+ cp ckan.exe dummy_ksp/ckan.exe
+ '[' jenkins = jenkins ']'
+ REGISTRY_FILE=/home/jenkins/.mono/registry/CurrentUser/software/ckan/values.xml
+ '[' -r /home/jenkins/.mono/registry/CurrentUser/software/ckan/values.xml ']'
+ rm -f /home/jenkins/.mono/registry/CurrentUser/software/ckan/values.xml
++ pwd
+ mono ckan.exe ksp add dummy /home/jenkins/workspace/NetKAN/dummy_ksp
Creating /home/jenkins/workspace/NetKAN/dummy_ksp/CKAN/downloads
Added "dummy" with root "/home/jenkins/workspace/NetKAN/dummy_ksp" to known installs
+ mono ckan.exe ksp default dummy
Successfully set "dummy" as the default KSP installation
++ pwd
+ mono ckan.exe repo add local file:///home/jenkins/workspace/NetKAN/master.tar.gz
Added repository 'local' - 'file:///home/jenkins/workspace/NetKAN/master.tar.gz'
+ mono ckan.exe repo remove default
Successfully removed "default"
+ ln -s downloads_cache dummy_ksp/CKAN/downloads
+ echo 'Running ckan update'
Running ckan update
+ mono ckan.exe update
Downloading updates...
Updated information on 500 available modules
+ echo 'Running ckan install -c built/*.ckan'
Running ckan install -c built/*.ckan
+ mono ckan.exe install -c 'built/*.ckan' --headless
Can not find file "built/*.ckan".
Exiting.
+ mono ckan.exe list --porcelain
+ mono ckan.exe show
show <module> - module name argument missing, perhaps you forgot it?
+ mono ckan.exe ksp forget dummy
Successfully removed "dummy"
Setting commit status on GitHub for https://github.com/KSP-CKAN/NetKAN/commit/ad5ef0af04301f339fc5c02e02abed1852905264
Setting commit status on GitHub for https://github.com/KSP-CKAN/NetKAN/commit/ad5ef0af04301f339fc5c02e02abed1852905264
Setting status of ad5ef0af04301f339fc5c02e02abed1852905264 to SUCCESS with url http://52.10.41.70/job/NetKAN/52/ and message: 'Build finished. No test results found.'
Finished: SUCCESS
```

**Comment by techman83** [comment]
@plague006 can you reference this issue in any builds that present this issue.

**Comment by Sigma88** [comment]
I'm not sure I understand the problem, let me know if I can be of any help

**Comment by techman83** [comment]
There are a number places it failed during the build process, yet as far as Jenkins was concerned it was a success. I've not had a chance to look at the script at all.

Jenkins like an CI platform, often uses exit codes and if the script 'Exit 0' it's going to think it's a success. When we were using travis each command would be defined in markup and the process would fail if any of them failed. It seems like there are circumstances where this isn't the case.

@Sigma88  - If you want to take a look, I'd totally appreciate it.

**Comment by plague006** [comment]
- [ ] KSP-CKAN/NetKAN#1916 - Success returned when success was expected, however according to its process it should have failed. `ERROR CKAN.RelationshipResolver (null) - Dependency on KerbinSide-core found, but nothing provides it.`

- [ ] KSP-CKAN/NetKAN#1895 - Success returned when success was expected, however it didn't actually test the mods in the PR and instead tested other non-related mods.

- [ ] KSP-CKAN/CKAN-meta#707 - Similar to KSP-CKAN/NetKAN#1895 except failure returned because the mods tested (not the mod in the PR) failed.

- [ ] KSP-CKAN/NetKAN#1896 KSP-CKAN/NetKAN#1920 KSP-CKAN/NetKAN#1875 KSP-CKAN/NetKAN#1920 KSP-CKAN/NetKAN#1901 - Success returned when failure was expected. Error in netkan generation `CKAN.FileNotFoundKraken` but build reports success.

- [ ] KSP-CKAN/NetKAN#1879 KSP-CKAN/CKAN-meta#698 - Failure returned when success was expected. In the dummy_ksp setup `ksp_version:any` means readme.txt's version is set to `any` resulting in `159 [1] ERROR CKAN.KSP (null) - Could not find KSP version in readme.txt`

- [X] KSP-CKAN/NetKAN#1886 - Success returned when success was expected, no error in this case. (Details in the PR).

I think that was all of them from the last couple days.

**Comment by techman83** [comment]
Thanks @plague006 - that's going to save lots of time trying to figure out what's going on :-)

**Comment by plague006** [comment]
KSP-CKAN/CKAN-meta#709 added to list

**Comment by techman83** [comment]
We might be seeing an issue that wrapping the command inside an if block causes with 'set -e' http://mywiki.wooledge.org/BashFAQ/105

The script could really use an overhaul in line with what @mgsdk did for NetKAN, so I will borrow some of it's functionality and apply it here.

**Comment by techman83** [comment]
I've done an overhaul of the CKAN-meta build script. I'll submit a PR, I've tested it on a handful of test and it appears to do what it says on the tin.

It's much more in line with the NetKAN build script now.

```
Installing mod "KerBalloons 1.1"
Unhandled Exception:
CKAN.FileNotFoundKraken: Trying to install KerBalloons 1.1, but it's not downloaded or download is corrupted
  at CKAN.ModuleInstaller.Install (CKAN.CkanModule module, System.String filename) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (ICollection`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: CKAN.FileNotFoundKraken: Trying to install KerBalloons 1.1, but it's not downloaded or download is corrupted
  at CKAN.ModuleInstaller.Install (CKAN.CkanModule module, System.String filename) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (ICollection`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
master u+2!CKAN-meta *> echo $?
1
```

```
Successfully removed "39246f3ade935636d11f813a56824562575e03a2"
+ for f in '${COMMIT_CHANGES}'
+ '[' build.sh = build.sh ']'
+ echo 'Lets try not to validate our build script with CKAN'
Lets try not to validate our build script with CKAN
+ continue
master u+2!CKAN-meta> echo $?
0
```

**Comment by techman83** [comment]
I'll do some testing of the above cases and see if I can reproduce the errors with the updated scripts. KSP-CKAN/CKAN-meta#711 + KSP-CKAN/NetKAN#1948

**Comment by techman83** [comment]
I've hand tested all the cases gathered up by @plague006 - KSP-CKAN/CKAN-meta#711 + KSP-CKAN/NetKAN#1948 are mergeable now.

## NetKAN
- [x] Should've passed but tests weren't run:
[NetKAN_1895.txt](https://github.com/KSP-CKAN/CKAN/files/1269/NetKAN_1895.txt)
[NetKAN_1916.txt](https://github.com/KSP-CKAN/CKAN/files/1268/NetKAN_1916.txt)
- [x] Success returned when error expected
[NetKAN_1898.txt](https://github.com/KSP-CKAN/CKAN/files/1270/NetKAN_1898.txt)
[NetKAN_1901.txt](https://github.com/KSP-CKAN/CKAN/files/1273/NetKAN_1901.txt)
- [x] Failure when version is any
[NetKAN_1879.txt](https://github.com/KSP-CKAN/CKAN/files/1274/NetKAN_1879.txt)

## CKAN-meta
- [x] Failure returned when mods not tested
[CKAN-meta_707.txt](https://github.com/KSP-CKAN/CKAN/files/1275/CKAN-meta_707.txt)
[CKAN-meta_709.txt](https://github.com/KSP-CKAN/CKAN/files/1276/CKAN-meta_709.txt)
- [x] Failure with version any
[CKAN-meta_698.txt](https://github.com/KSP-CKAN/CKAN/files/1277/CKAN-meta_698.txt)

**Comment by plague006** [comment]
@techman83 put a bunch of work into the build scripts and things have been running smooth for months.
