### ISSUE TITLE
[Feature] Right-click context menu on MainModList

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2180]
If we can implement a right-click context menu on the main mod list, it could be the easy gateway to loads of extra functionality. 

**@Olympic1's progress:**
- [x] A clean implementation of mod replacements - #2671
- [x] A `Reinstall` option - #2202
- [x] Select specific version of a mod to install - #2364
- [x] A `Download contents` option - #2202
- [ ] A way to override the autodetected mods so CKAN can control them - #2186 / #949
- [x] A way to add an externally downloaded zip to the cache - #2246
- [ ] And if we ever want to add user tagging of mods, this would be the way to manipulate those:
- - [ ] A way to mark mods - #2176
- - [ ] A way to hide mods from all filters - #2082
- - [ ] An `Add to favourites` option - #1677
- - [ ] Set priority for mods - #1375

We could also display specific conflict information in the context menu
It would also be a good idea to add a "Status" column.

**Comment by APAeroDan** [comment]
I think my issue would tie into this nicely. #2186

**Comment by Olympic1** [comment]
I worked on this a bit and have it working now. What functions do you guys want for the next release?

**Comment by APAeroDan** [comment]
I would love an autodetect override.  I've had several instances where I had the mod preinstalled and I wanted ckan to takeover.  Right now, I have to uninstall the mods before it will do that, and then it auto uninstalls any dependant mods.  So to fix, one has to go through 3 uninstall reinstall cycles... Gets old.  If there were any override, then it would bypass the dependency uninstall.

**Comment by Olympic1** [comment]
Added it to the list and will investigate how to override the `AD` marked mods.

**Comment by politas** [comment]
Feel free to do a PR with only partial functionality. Just getting the basic menu in place is the critical thing, then we can add to it. Thank you thank you thank you for working on this! I've been distracted by other things that have stopped me being able to dive into it.

**Comment by politas** [comment]
I'd really like to use this for the GUI implementation in #1888

**Comment by APAeroDan** [comment]
I've got some programming experience, but it is in firmware.  I've been
meaning to learn GUI.  What is this mod written in?

**Comment by Olympic1** [comment]
> Feel free to do a PR with only partial functionality.

Ok, I'll work out the last bugs and will then make a PR.

> What is this mod written in?

The GUI is written in .NET's library `Windows Forms (WinForms)`

**Comment by yalov** [comment]
-   A way to mark mods #2176
-   An Add to favourites option #1677
-  Set priority for mods #1375

They are pretty same thing.
instead of "star" at #1677 and "question_mark" at #2176 it can be ❶❷❸❹❺. 

Maybe better and simpler not integrate that at "installed" column (as I draw at #2176), but add new column with these. Then mod can be marked/installed independently.

**Comment by politas** [comment]
> They are pretty much the same thing.

Sure, and we haven't yet made a decision which way to go. Each proposal has a slightly different use case, though, so we may end up implementing more than one.

**Comment by Mengmoshu** [comment]
Since I came here looking for "favorites" functionality, I just wanted to add a little support to "a way to mark mods".

I'm new to modding KSP, and thus using CKAN, so I'm trying to keep my modlist small. But it would be pretty nice to mark mods that look interesting so I can check them out after I have more experience.
