### ISSUE TITLE
[Feature] KSP2 support plans

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2863]
## Motivation

KSP2 has been announced:

- https://forum.kerbalspaceprogram.com/index.php?/topic/187313-we-are-excited-about-kerbal-space-program-2/
- https://forum.kerbalspaceprogram.com/index.php?/topic/187315-kerbal-space-program-2-master-post/

This raises the question of how CKAN should handle the sequel. I'll assume for now that we want to index mods for it and will be able to do so. (If we decide we want nothing to do with KSP2, or if we can't due to some hypothetical exclusive deal with Twitch, then that's obviously far simpler.)

This is a WIP issue to track discussion and hash out a concrete plan. Please reply with further thoughts, considerations, etc.

## Questions

- [x] Will mods still work the same way? Unzip files into a folder like GameData?
- [x] How can we determine the installed version? Is buildID.txt still there?
- [x] [Will KSP1 ever release a 2.0 version within its numbering scheme?](https://forum.kerbalspaceprogram.com/index.php?/topic/187315-kerbal-space-program-2-master-post/&do=findComment&comment=3667823)
  - 1.9 will be followed by 1.10
    https://forum.kerbalspaceprogram.com/index.php?/topic/193978-kerbal-space-program-esa-110-update-sharedhorizons/
  - 1.12.3 is the final update of KSP1

## Issues

- [x] Shouldn't have to download 20+ MB of metadata for KSP1 that you'll never use (see #1975)

## Tasks

Client updates to support the new game:

- [x] Version detector
- [x] Game folder paths

Infrastructure:

- [x] Split NetKAN metadata into `NetKAN/KSP1` and `KetKAN/KSP2` subdirs?
- [x] Split CKAN-meta somehow so you only download the metadata you need

**Comment by politas** [comment]
We already had plans to split CKAN-meta up to lower the download burden. I'd like to see a system where there is a separate metadata file for each major point version, downloaded according to KSP version compatibility settings and merged as required. That would make supporting KSP 2 pretty seamless.

**Comment by techman83** [comment]
There is an unmerged branch in the old bot where I came up with some logic for this. That was extendable based on some JSON config. It will need a slight re-think, but I reckon we could come up with something with the new architecture (though we've got a bit of a backlog to clean up and get merged in).

**Comment by HebaruSan** [comment]
New timeline from the devs:

https://forum.kerbalspaceprogram.com/index.php?/topic/210187-kerbal-space-program-2-release-into-early-access-feb-24th/

- 2023-02-24 (time of day unknown)
- $49.99 (subject to change by vendors), to be increased for 1.0
- Early access
- PC only (Mac and Linux on the "extended roadmap")
- Missing most of the big headlining features originally announced (still in progress, to be added when ready)
- From Steam, Epic Games, and KSP store

Players may be expected to treat this as a full release in terms of expecting CKAN support. So we'll probably have to cough up fifty bucks to keep up with that, unless we can get in onto some kind of closed beta team.

**Comment by sundhaug92** [comment]
Could it be an idea to rewrite the history on the metadata repo so that you have one branch for each game? Then you could do a dumb pull to get the refs for each branch and only download the data for each. Could also move older versions of mods to a separate repo.

**Comment by HebaruSan** [comment]
Summary of current situation:

- The game supposedly has an incomplete built-in mod loader that doesn't actually run the mods yet
- To work around that, there are two third party mod loaders competing for early internet fame and glory
- Supposedly mods using the built in loader will have to be packaged in Unity addressable asset bundles, so ZIP files may or may not still be viable for distribution (the third party ones look like they allow loose files put into specific folders)
- The built in loader parses a new JSON mod info format, which Netkan might be able to scrape for metadata
- There are some rough early mods already on SpaceDock:
  https://spacedock.info/kerbal-space-program-2/browse/top

It should stabilize significantly once the official mod loader is completed and released.

**Comment by HebaruSan** [comment]
A user donated me the game!

- There's no `buildID.txt`; the main folder contains only:
  - `KSP2_x64.exe`
  - `UnityCrashHandler64.exe`
  - `UnityPlayer.dll`

  That's a problem for selecting a file to add an instance and for determining the game version. I don't see any fallback sources for version info, either.
- There's no `GameData`, consistent with the bundle thing

**Comment by HebaruSan** [comment]
The `KSP2_x64.exe` file has the version info in the Properties window:

![image](https://user-images.githubusercontent.com/1559108/221733422-52a2204c-92af-4815-91ed-70b00ca72890.png)

**Comment by HebaruSan** [comment]
Of the mods currently on SpaceDock, 3 use BepInEx and 10 use SpaceWarp.

They install mods at:

- `<GameRoot>/SpaceWarp/Mods`
- `<GameRoot>/BepInEx/plugins`

So if we try to support these, we'd effectively need to have two replacements for `GameData`.

**Comment by HebaruSan** [comment]
Wow, that more or less works!

![image](https://user-images.githubusercontent.com/1559108/221742022-188f1faf-a9a0-4a4d-91a6-10e813451b2c.png)

**Comment by HebaruSan** [comment]
Oh lovely, SpaceWarp and BepInEx have a file conflict! They both want to create `<GameRoot>/doorstop_config.ini`, with different, conflicting contents (excerpts only here to show up to the target assembly arguments):

```ini
[UnityDoorstop]
# Specifies whether assembly executing is enabled
enabled=true
# Specifies the path (absolute, or relative to the game's exe) to the DLL/EXE that should be executed by Doorstop
targetAssembly=BepInEx\core\BepInEx.Preloader.dll
```

```ini
# General options for Unity Doorstop
[General]

# Enable Doorstop?
enabled=true

# Path to the assembly to load and execute
# NOTE: The entrypoint must be of format `static void Doorstop.Entrypoint.Start()`
target_assembly=SpaceWarp/Core/SpaceWarp.dll
```

So if you try to install both manually, presumably only the second one you install will work. And CKAN would just barf during the second install, if these were both CKAN modules.

**Comment by Grumalg** [comment]
Scroll down to a post by rofl47 discussing a possible solution.  BepInEx seems to have a SpaceWarp loader inside it.  Mixed results in following posts below, but it might lead to something...
https://forum.kerbalspaceprogram.com/index.php?/topic/212355-bepinex-for-ksp-2-adding-modding-support-to-the-game/

**Comment by HebaruSan** [comment]
I guess if these were to be added to CKAN metadata today, we'd:

- Index [BepInEx](https://spacedock.info/mod/3255/BepInEx%20for%20KSP%202) as-is
- Index [BepInEx Space Warp Plugin](https://spacedock.info/mod/3277/BepInEx%20Space%20Warp%20Plugin) with BepInEx as a dependency and call it `SpaceWarp`
- Ignore the [standalone SpaceWarp](https://spacedock.info/mod/3257/Space%20Warp) (which is currently the most downloaded file for KSP2 on SpaceDock by a factor of ~2.5), since it conflicts with BepInEx

**Comment by HebaruSan** [comment]
@techman83, after hacking on this for a couple of hours, I think we should create two new repos:

- KSP-CKAN/KSP2-NetKAN
- KSP-CKAN/KSP2-CKAN-meta

This would create a nice clean separation between the two games. Then we should be able to configure new instances of the Scheduler, Inflator, and Indexer to use these once the Inflator is updated with multi-game support (in progress now).

I have local first drafts of these repos (no `.git` folder but some handcrafted metadata for 4 mods for testing), and it's all going pretty smoothly so far.

![image](https://user-images.githubusercontent.com/1559108/221978883-a0906726-c2c5-4674-a491-cf20b6180d7d.png)

**Comment by HebaruSan** [comment]
One wrinkle that'll likely need massaging: GitHub gave us `main` branches instead of `master` for the new repos, which might cause some complications for the Infra. We talked about making that change anyway, but it looks like now is the time.

**Comment by cgruber** [comment]
For historical compatibility, if you want to change the historical versions to use `main` it's entirely possible to just regularly sync `master` so that it's always up to date with main. Just do a fast-forward merge and push. This could be done as a part of github actions pipelines. Could keep that running indefinitely, or for a long while to ensure older clients work for however long you want them to.
